name: Selenium E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install -U selenium
          pip install pytest
          pip install webdriver-manager
          pip install selenium pytest webdriver-manager

      - name: Run tests
        run: |
          pytest tests/specs/
