name: Selenium E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Cambiado a una versión más reciente compatible

      # Instalar dependencias
      - name: Install dependencies
        run: |
          pip install -U selenium
          pip install pytest
          pip install webdriver-manager
      # Ejecutar las pruebas
      - name: Run tests
        env:
          DISPLAY: ":99" # Required for graphical interfaces in headless mode
        run: |
          pytest tests/specs/
